version: '3'
services:
  app:
    build: .
    depends_on:
      - postgres
    ports:
      - "3000:3000"
  postgres:
    image: postgres:11-alpine
    environment:
      POSTGRES_PASSWORD: postgres
